### PR TITLE
Update to version 0.7.13.

### PR DESCRIPTION
**Pull request by tobiasraabe**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi,

since I received no answer on #17, this is my attempt to see why the pipeline failed because the build reports seem to be deleted. I didn't mean to step on anybody's toes if this is not the right approach.

### CODE REVIEW

**Comment by tobiasraabe** [comment]
@conda-forge-admin, please rerender

**Comment by tobiasraabe** [comment]
Hi @dharhas and @sdc50,

the important modification is in eb4db6a which works at least for version 0.7.13. Could you merge this PR or roll out the change to the existing PRs?

Thank you very much!

**Comment by Hoeze** [comment]
Having up-to-date pony in conda would be very much appreciated :)

**Comment by tobiasraabe** [comment]
Hi @conda-forge/core,

I did not get a response from the maintainers of the repo for two weeks on an issue and this PR combined. The last release is more than a year ago although new versions of the package have been released on PyPI. Can you help?

**Comment by synapticarbors** [comment]
Thanks for alerting us to this. I'm going to do a few things in the PR opened by the regrobot, but will get the newest version up soon.

**Comment by synapticarbors** [comment]
superseded by #16

**Comment by synapticarbors** [comment]
@tobiasraabe -- thanks for putting in this pull request. I wanted to do a few other clean-up things, so I made changes in the regrobot's original PR for this version. I've also added myself as a co-maintainer since the feedstock seemed abandoned.

**Comment by tobiasraabe** [comment]
Thank you very much, @synapticarbors! This is fantastic :).

**Pull request closed without merging**
